#!/bin/bash

create database lojao;

use lojao;

create table produtos(
id integer not null auto_increment primary key,
nome varchar(255),
preco decimal(10,2),
descricao text,
categoria_id integer,
usado boolean default false
);

create table categorias(
id integer not null auto_increment primary key,
nome varchar(255)
);
